language: c++

compiler:
  - gcc
  - clang

script:
  - cd `mktemp -d` && pwd
  - sudo apt-get update && sudo apt-get install libboost-dev
  - mkdir -vp ${TRAVIS_BUILD_DIR}/m4
  - autoreconf -ivf ${TRAVIS_BUILD_DIR}
  - ${TRAVIS_BUILD_DIR}/configure --prefix=`mktemp -d`
  - make
  - make dist
